### ISSUE TITLE
Seems the site right now has some invalid TLS certificate for the API route

### ISSUE THREAD

**Issue by trailblazr** [StevenKowalzik/Mensa-Bremen-API#32]
right now provides a

```
404 Not Found
nginx/1.10.3 (Ubuntu)
```

**Comment by trailblazr** [comment]
thx, works great again. remind me that i share my **lunchbot** i did to provide automatic lunch telegrams also in english language and posting them to Microsoft Teams channels.

**Comment by StevenKowalzik** [comment]
Oh that’s great, happy to hear that this is actually being used! I feel like i have to optimize and update this project, has been quite some time.
